### ISSUE TITLE
As a user, I want to be able "like" another user's bookmark, so that it will appear on my personal bookmark index.

### ISSUE THREAD

**Issue by pdbradley** [biblesforamerica/blocsocial#6]

**Comment by pdbradley** [comment]
Generally this requires a join table (likes?) with a user_id and a bookmark_id, and something in the model like this:

def User
has_many liked_bookmarks, through: likes
end

def Bookmark
has_many likers, through: likes
end

**Comment by pdbradley** [comment]
creating a branch called "likeability"

**Comment by hdfelix** [comment]
Started this this with Eric today;

**Comment by bfaguy** [comment]
@hdfelix, @echen1031,
I'm a little concerned that we are writing duplicate code. 
@iedidiah and I began to write the 'my bookmarks' page under bookmarks / index.html.erb
and it looks like you might be doing the same thing under likes / index.html.erb

**Comment by hdfelix** [comment]
Hi brothers, 

The way I understand it is that `bookmarks#index` should be **all** the bookmarks once an user is signed in (the index for all the bookmarks); `likes#index` should display **only** the bookmarks the signed in user has liked or added (b/c the Likes class is the association table joining users and liked bookmarks):  

```
  create_table "likes", force: true do |t|
    t.integer  "bookmark_id"
    t.integer  "user_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end
```

So in summary:
- **Welcome#index** - signed out welcome view (no mockup)
- **Bookmarks#index** - all the bookmarks that have been marked by all users, displayed by tag (first mockup)
- **Likes#index** - the bookmarks liked by the signed in user (the last mockup)

**Comment by pdbradley** [comment]
A good principle to hold to for controllers is that they should relate to the model they are named after in their actions.  For example, it isn't good for a likescontroller to have an index action that actually instantiates @bookmarks.      I mean it isn't a law, but it can get confusing.  It would be better to create another collection route in the bookmark controller called "liked" that would list all the liked bookmarks.  If you look in the rails guides about routing, and seach for the word collection you can see some examples

**Comment by hdfelix** [comment]
Thanks Philip. So then so how do you handle all bookmarks vs my bookmarks (vs liked bookmarks)?

Do we create a home controller and index to display the bookmarks for all users (mockup 1)?

And how would we handle bookmarks under tags displayed  as, eg., 'blockmarks.com/inspirational' (from the mockups)?
